"""empresa aberta

Revision ID: 0f3d101b9526
Revises: 4fe4b6a5a4a7
Create Date: 2025-05-26 09:59:46.118350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3d101b9526'
down_revision = '4fe4b6a5a4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aberto', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('aberto')

    # ### end Alembic commands ###
