"""Coluna criacao para todos os dates

Revision ID: 4fe4b6a5a4a7
Revises: cbfdc5fb974f
Create Date: 2025-05-25 12:10:09.198587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe4b6a5a4a7'
down_revision = 'cbfdc5fb974f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from datetime import datetime
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criacao', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))

    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criacao', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criacao', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criacao', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('criacao')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('criacao')

    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_column('criacao')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('criacao')

    # ### end Alembic commands ###
